import {describe,it,expect} from 'vitest';
import {HttpMarketplaceAdapter,EnvAccessTokenProvider,Service,type D1,type MarketplaceAdapter} from '../src/index';

const token=new EnvAccessTokenProvider('synthetic-token');
const request=(status=200,body:any={})=>{const seen:any[]=[];const f=async(input:RequestInfo|URL,init?:RequestInit)=>{seen.push({url:String(input),init});return new Response(status===204?null:JSON.stringify(body),{status,headers:{'content-type':'application/json'}})};return {seen,f}};
describe('HttpMarketplaceAdapter production contract',()=>{
 it('GET question uses encoded id and bearer header',async()=>{const x=request(200,{id:'q 1',item_id:'TST1',seller_id:'1',status:'UNANSWERED',text:'x'}),a=new HttpMarketplaceAdapter(token,x.f);await a.getQuestion('q 1');expect(x.seen[0]).toEqual({url:'https://api.mercadolibre.com/questions/q%201',init:{method:'GET',headers:{authorization:'Bearer synthetic-token'},body:undefined}})});
 it('GET questions uses item query and validates array',async()=>{const x=request(200,{questions:[]}),a=new HttpMarketplaceAdapter(token,x.f);await expect(a.listQuestions('TST 1')).resolves.toEqual([]);expect(x.seen[0].url).toBe('https://api.mercadolibre.com/questions/search?item_id=TST%201')});
 it('POST answer has exact JSON contract',async()=>{const x=request(204,{}),a=new HttpMarketplaceAdapter(token,x.f);await a.answerQuestion('q1','yes');expect(x.seen[0]).toEqual({url:'https://api.mercadolibre.com/answers',init:{method:'POST',headers:{authorization:'Bearer synthetic-token','content-type':'application/json'},body:'{"question_id":"q1","text":"yes"}'}})});
 it('PUT attributes has exact JSON contract',async()=>{const x=request(204,{}),a=new HttpMarketplaceAdapter(token,x.f);await a.putItemAttributes('TST1',[{id:'BRAND',value_name:'Example'}]);expect(x.seen[0]).toEqual({url:'https://api.mercadolibre.com/items/TST1',init:{method:'PUT',headers:{authorization:'Bearer synthetic-token','content-type':'application/json'},body:'{"attributes":[{"id":"BRAND","value_name":"Example"}]}'}})});
 it('GET item uses no body',async()=>{const x=request(200,{id:'TST1',seller_id:'1',status:'active',attributes:[]}),a=new HttpMarketplaceAdapter(token,x.f);await a.getItem('TST1');expect(x.seen[0].init.body).toBeUndefined();expect(x.seen[0].init.method).toBe('GET')});
 it('fails closed without token',async()=>await expect(new HttpMarketplaceAdapter(new EnvAccessTokenProvider(),request().f).getItem('x')).rejects.toThrow('oauth_read_only_unavailable'));
 it.each([400,401,403,404,409,429,500,503])('maps upstream status %i',async(status)=>await expect(new HttpMarketplaceAdapter(token,request(status,{}).f).getItem('x')).rejects.toThrow('upstream_'+status));
 it.each([{questions:null},{questions:{}},{}, {questions:'bad'}])('rejects malformed questions %o',async(body)=>await expect(new HttpMarketplaceAdapter(token,request(200,body).f).listQuestions('x')).rejects.toThrow('question_contract_changed'));
 it.each([{id:'x'},{id:'x',status:1},{id:'x',status:'active',sub_status:'bad'},{id:'x',status:'active',sub_status:[1]},{id:'x',status:'active',sub_status:[],non_selling_reason:1}])('moderation adapter rejects hostile shape',async(body)=>await expect(new HttpMarketplaceAdapter(token,request(200,body).f).getItemModeration('x')).rejects.toThrow('moderation_contract_changed'));
 it('moderation adapter returns allowlisted shape',async()=>await expect(new HttpMarketplaceAdapter(token,request(200,{id:'x',status:'active',sub_status:['warning'],non_selling_reason:null}).f).getItemModeration('x')).resolves.toEqual({id:'x',status:'active',sub_status:['warning'],non_selling_reason:null}));
});
class ProductD1 implements D1 { constructor(private row:any){} prepare(_sql:string){const row=this.row;const statement={bind:(..._v:any[])=>statement,first:async()=>row,run:async()=>({meta:{changes:1}})};return statement} }
class Noop implements MarketplaceAdapter { async getQuestion(){return {}} async listQuestions(){return []} async answerQuestion(){} async getItem(){return {}} async putItemAttributes(){} async getItemModeration(){return {}} }
const valid={aliases:['alias-one'],version:'v1',attributes:[{id:'BRAND',value_name:'Example'}]};
describe('registry and receipt identity',()=>{
 it('loads validated D1 definition',async()=>{const s:any=new Service({DB:new ProductD1({product_key:'d1-key',seller_id:'10000003',item_id:'TST100000003',config_json:JSON.stringify(valid)})} as any,new Noop());expect(await s.product('alias-one')).toMatchObject({product_key:'d1-key',seller_id:'10000003'})});
 it.each([{}, {product_key:'x'}, {product_key:'x',aliases:[],seller_id:'1',item_id:'x',version:'v1',attributes:[{id:1}]}])('rejects invalid D1 product %o',async(config)=>{const s:any=new Service({DB:new ProductD1({product_key:'x',seller_id:'1',item_id:'TST1',config_json:JSON.stringify(config)})} as any,new Noop());expect(await s.product('x')).toBeNull()});
 it('loads documented JSON registry',async()=>{const s:any=new Service({DB:new ProductD1(null),PRODUCT_REGISTRY_JSON:JSON.stringify([{product_key:'json-key',seller_id:'10000004',item_id:'TST100000004',...valid}])} as any,new Noop());expect(await s.product('alias-one')).toMatchObject({product_key:'json-key'})});
 it('two prepared receipts never use timestamp-only identity',async()=>{const ids=new Set<string>();for(let i=0;i<128;i++)ids.add(crypto.randomUUID());expect(ids.size).toBe(128)});
});
